### PR TITLE
Add `clickfinger` in touchpad config

### PR DESCRIPTION
**Pull request by uetcis**
This PR adds the [clickfinger behavior](https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html#clickfinger-behavior) setting for touchpads.

I have tested live reload and it works well on my machine.

### CODE REVIEW

**Comment by YaLTeR** [comment]
Thanks! Hmm, so it seems that on my Apple Magic Trackpad 2 clickfinger is set by default, but on my laptop touchpad it's not. To preserve this behavior, I think it's better to make it into a `click-method` which can be set to `button-areas` or `clickfinger` (or left to default if unset). This is also consistent with what you can set in sway-input.

**Comment by uetcis** [comment]
> Thanks! Hmm, so it seems that on my Apple Magic Trackpad 2 clickfinger is set by default, but on my laptop touchpad it's not. To preserve this behavior, I think it's better to make it into a `click-method` which can be set to `button-areas` or `clickfinger` (or left to default if unset). This is also consistent with what you can set in sway-input.

Sure, I'll change it tomorrow

**Comment by uetcis** [comment]
@YaLTeR I've changed the `clickfinger` setting into `click-method`, could you take a look at it?

**Comment by YaLTeR** [comment]
Thanks, works well! Did some minor tweaks.

**Pull request merged**
