### PR TITLE
Change the momentary dark red screen before locking to black

### PR DESCRIPTION
**Pull request by salman-farooq-sh**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Uh, no, it's red for a reason. If your screen locker crashes, it hints you that the session is locked, and you don't have a random blackscreen.

A proper fix is to wait until the screen locker surface appears with a timeout before drawing it.

**Comment by salman-farooq-sh** [comment]
@YaLTeR But https://github.com/YaLTeR/niri/issues/808#issuecomment-2512158069 ?

**Comment by YaLTeR** [comment]
Yes, I meant that you can personally hardcode it in that place in your own build

**Comment by salman-farooq-sh** [comment]
Umm, would everyone else also prefer having the red screen not flashing every time when locking at the cost of losing a hint that their locker has crashed? I mean we can definitely change this back to red once the proper fix is done. Hmmm, locker crashing can be tricky to debug indeed if it looks just the same as everything else black so maybe a much darker red or other color?

**Comment by salman-farooq-sh** [comment]
How often do lockers crash? I don't think swaylock has ever crashed for me.

**Comment by YaLTeR** [comment]
Does a screen transition not work for you?

**Comment by salman-farooq-sh** [comment]
A screen transition also works but with that you can't use wallpapers in swaylock which are slow to load because then you either have to increase the transition time which makes the system feel less snappy or you are restricted to using light-weight wallpapers.

I can live with manually timing the screen transition for every wallpaper but putting the laptop in power-saving profile also affects the swaylock showing on screen time.

**Comment by salman-farooq-sh** [comment]
@YaLTeR ping

**Comment by YaLTeR** [comment]
Why? I explained why I want to keep the background red and solve the flash differently (by waiting until a surface appears before drawing the locked screen).

**Comment by salman-farooq-sh** [comment]
> A screen transition also works but with that you can't use wallpapers in swaylock which are slow to load because then you either have to increase the transition time which makes the system feel less snappy or you are restricted to using light-weight wallpapers.
> 
> I can live with manually timing the screen transition for every wallpaper but putting the laptop in power-saving profile also affects the swaylock showing on screen time.

I meant w.r.t this, like... the screen is essentially stuck until the transition delay completes. Besides this I don't have any reason for this PR and yes you are right about the correct solution and this indeed is workaround-ish at best. Anyways, if you think this reason alone is not enough then you can close this PR. Thanks :)

**Comment by salman-farooq-sh** [comment]
Especially when the laptop is in power-saving mode, the time taken to show the wallpaper by swaylock is a lot at least for me.

**Comment by YaLTeR** [comment]
Could you check that happens on sway if you enable power saving and run swaylock with one of the heavy wallpapers? Do you see red or black for a while or frozen screen? 

Either way you can apply the patch locally until a proper fix is in place; it likely won't break.

**Comment by salman-farooq-sh** [comment]
Nevermind, just tried hyprlock and it's blazing fast with its own transition I think so that solves that. Closing. Thanks.

**Comment by YaLTeR** [comment]
Nice; still if you could check what happens on sway with swaylock that would be helpful

**Comment by salman-farooq-sh** [comment]
Just checked sway with swaylock and it shows a pitch black screen before the wallpaper shows up. I am now actually having difficulty forming an opinion what color niri should have.

**Comment by YaLTeR** [comment]
Thanks

**Comment by Vortriz** [comment]
> Nevermind, just tried hyprlock and it's blazing fast with its own transition I think so that solves that. Closing. Thanks.

heyy can you elaborate on what setting did you in hyprlock to deal with that red splash screen?

**Comment by salman-farooq-sh** [comment]
@Vortriz Sorry for the late reply but there was still a tiny amount of time the red splash showed up even with hyprlock. I just learned to live with it.

**Comment by txkyel** [comment]
@Vortriz the suggestion to use `do-screen-transition` in https://github.com/YaLTeR/niri/issues/808#issuecomment-2480534649 works for me to hide the red splash screen. I imagine that the crossfade with `do-screen-transition` might interfere the hyprlock fade in animation but I can't really notice much a difference.

**Comment by YaLTeR** [comment]
fwiw this has been fixed on main. Together with disabling the hyprlock fade it makes for no red flash

**Comment by Vortriz** [comment]
yupp, `--no-fade-in` works. @txkyel cool trick nonetheless.

**Pull request closed without merging**
